name = "edge-feeds"

pages_build_output_dir = "dist"

compatibility_date = "2024-11-06"
compatibility_flags = [ "nodejs_compat" ]

[[kv_namespaces]]
binding = "KV"
id = "b519bdc52614434691f3a3b00da1bf4e"
